# Generated by Django 4.1.1 on 2022-10-22 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('symboling', models.SmallIntegerField()),
                ('carname', models.CharField(max_length=50)),
                ('fueltype', models.CharField(max_length=50)),
                ('aspiration', models.CharField(max_length=50)),
                ('doornumber', models.CharField(max_length=50)),
                ('carbody', models.CharField(max_length=50)),
                ('drivewheel', models.CharField(max_length=50)),
                ('enginelocation', models.CharField(max_length=50)),
                ('wheelbase', models.PositiveIntegerField()),
                ('carlength', models.PositiveIntegerField()),
                ('carwidth', models.PositiveIntegerField()),
                ('carheight', models.PositiveIntegerField()),
                ('curweight', models.PositiveIntegerField()),
                ('enginetype', models.CharField(max_length=50)),
                ('cylindernumber', models.CharField(max_length=50)),
                ('enginesize', models.PositiveIntegerField()),
                ('fuelsystem', models.CharField(max_length=50)),
                ('boreratio', models.PositiveIntegerField()),
                ('stoke', models.PositiveIntegerField()),
                ('compressionratio', models.PositiveIntegerField()),
                ('horsepower', models.PositiveIntegerField()),
                ('peakrpm', models.PositiveIntegerField()),
                ('citympg', models.PositiveIntegerField()),
                ('highwaympg', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
