# Generated by Django 4.1.1 on 2022-10-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_ID3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='curweight',
            new_name='curbweight',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='stoke',
            new_name='stroke',
        ),
    ]
