# Generated by Django 4.1.1 on 2022-10-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_ID3', '0002_rename_curweight_car_curbweight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='boreratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='carheight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='carlength',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='carwidth',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='citympg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='compressionratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='curbweight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='enginesize',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='highwaympg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='horsepower',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='peakrpm',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='stroke',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='symboling',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='wheelbase',
            field=models.FloatField(),
        ),
    ]
