-- A. SQLite Basic SELECT statement
-- 1. Write a query to display the names (first_name, last_name) using alias name "First Name", "Last Name".
--SELECT first_name as "First Name", last_name as "Last Name" FROM employees;
-- 2. Write a query to get unique department ID from employee table.
--SELECT DISTINCT department_id FROM employees;
-- 3. Write a query to get all employee details from the employee table order by first name, descending.
--SELECT * FROM employees ORDER BY first_name DESC;
-- 4. Write a query to get the names (first_name, last_name), salary, PF of all the employees (PF is calculated as 12% of salary). 
--SELECT first_name || ' ' || last_name as name, salary, salary*0.12 as PF FROM employees;
-- 5. Write a query to get the employee ID, names (first_name, last_name), salary in ascending order of salary.
--SELECT employee_id, first_name ||' ' || last_name as name, salary FROM employees ORDER BY salary ASC;
-- 6. Write a query to get the total salaries payable to employees. 
--SELECT SUM(salary) as sum_salary FROM employees;
-- 7. Write a query to get the maximum and minimum salary from employees table.
--SELECT MAX(salary) as max_salary, MIN(salary) as min_salary FROM employees;
-- 8. Write a query to get the average salary and number of employees in the employees table. 
--SELECT SUM(salary)/COUNT(salary) as average_salary, COUNT(employee_id) as number_of_employee FROM employees;
-- 9. Write a query to get the number of employees working with the company.
--SELECT COUNT(*) as 'number of employees' FROM employees;
-- 10. Write a query to get the number of jobs available in the employees table.
--SELECT COUNT(DISTINCT job_id) as jobs_available FROM employees;
-- 11. Write a query get all first name from employees table in upper case.
--SELECT upper(first_name) as first_name FROM employees;
-- 12. Write a query to get the first 3 characters of first name from employees table.
--SELECT substr(first_name, 0,4) as first_name FROM employees;
-- 13. Write a query to calculate 171*214+625.
--SELECT 171*214+625 as calculate;
-- 14. Write a query to get the names (for example Ellen Abel, Sundar Ande etc.) of all the employees from employees table.
--SELECT first_name || ' ' || last_name as name FROM employees;
-- 15. Write a query to get first name from employees table after removing white spaces from both side. 
--SELECT REPLACE(first_name,' ', '') as first_name FROM employees;
-- 16. Write a query to get the length of the employee names (first_name, last_name) from employees table.
--SELECT first_name || ' ' || last_name as name,length(first_name || ' ' || last_name) as 'length of name' FROM employees;
-- 17. Write a query to select first 10 records from a table.
--SELECT * FROM employees LIMIT 10;
-- 18. Write a query to get monthly salary (round 2 decimal places) of each and every employee?
SELECT first_name || ' ' || last_name as name, round(salary,2) as salary FROM employees;