-- C. Aggregate Functions and Group by

-- 1. Write a query to list the number of jobs available in the employees table. 
--SELECT DISTINCT job_id FROM employees;
-- 2. Write a query to get the total salaries payable to employees.
--SELECT SUM(salary) as sum_salary FROM employees;
-- 3. Write a query to get the minimum salary from employees table.
--SELECT MIN(salary) as min_salary FROM employees;
-- 4. Write a query to get the maximum salary of an employee working as a Programmer. 
--SELECT MAX(salary) as max_salary FROM employees;
-- 5. Write a query to get the average salary and number of employees working the department 90.
--SELECT SUM(salary) FROM employees WHERE department_id = 90;
-- 6. Write a query to get the highest, lowest, sum, and average salary of all employees.
--SELECT MAX(salary) as max_salary, MIN(salary) as min_salary,SUM(salary) as sum_salary, SUM(salary)/COUNT(salary) as average_salary FROM employees;
-- 7. Write a query to get the number of employees with the same job. 
--SELECT COUNT(*) as 'number of employees', job_id FROM employees GROUP BY job_id;
-- 8. Write a query to get the difference between the highest and lowest salaries. 
--SELECT MAX(salary)-MIN(salary) as 'difference between the highest and lowest salary' FROM employees;
-- 9. Write a query to find the manager ID and the salary of the lowest-paid employee for that manager.
--SELECT manager_id FROM employees WHERE salary = (SELECT MIN(salary) as salary FROM employees);
-- 10. Write a query to get the department ID and the total salary payable in each department. 
--SELECT department_id, SUM(salary) as 'the total salary payable' FROM employees GROUP BY department_id;
-- 11. Write a query to get the average salary for each job ID excluding programmer. 
-- SELECT SUM(salary)/COUNT(salary) as average_salary, job_id
-- FROM (SELECT salary, job_id FROM employees WHERE job_id <> 'IT_PROG')
-- GROUP BY job_id;
-- 12. Write a query to get the total salary, maximum, minimum, average salary of employees (job ID wise), for department ID 90 only.
-- SELECT  MAX(salary) as max_salary, 
--         MIN(salary) as min_salary,
--         SUM(salary) as sum_salary, 
--         SUM(salary)/COUNT(salary) as average_salary 
-- FROM employees WHERE department_id = 90;
-- 13. Write a query to get the job ID and maximum salary of the employees where maximum salary is greater than or equal to $4000.
-- SELECT job_id, salary as 'max salary'
-- FROM (SELECT MAX(salary) as salary, job_id FROM employees GROUP BY job_id)
-- WHERE salary >= 4000;
-- 14. Write a query to get the average salary for all departments employing more than 10 employees.
SELECT SUM(salary)/COUNT(salary) as average_salary, department_id FROM employees GROUP BY department_id HAVING COUNT(*)>10;
