# Generated by Django 4.1.3 on 2022-11-11 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about_pro', models.CharField(max_length=500)),
                ('tech_used', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=500)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
