# Generated by Django 4.1.3 on 2022-11-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
